# If serverUrl.isEmpty() ? embedded mode : tournament mode
# If tournament mode without tournamentUrl : connect to sim directly
application:
    mode: tournament
    connect:
        machineName:
        serverUrl:
        tournamentUrl:
        tournamentLogin: /faces/visualizerLogin.jsp
    # Set number of milliseconds to pause for each timeslot during log replay
    timeslotPause: 0
