version: '2'
services:
    visualizer2-app:
        image: visualizer2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://visualizer2-mysql:3306/visualizer2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    visualizer2-mysql:
        extends:
            file: mysql.yml
            service: visualizer2-mysql
